package net.devemperor.dictate.core

import net.devemperor.dictate.ai.conversation.ReconstructedTurn
import net.devemperor.dictate.ai.runner.ConversationResult
import net.devemperor.dictate.database.DictateDatabase
import net.devemperor.dictate.database.entity.CompletionLogEntity
import net.devemperor.dictate.database.entity.ConversationMessageEntity
import net.devemperor.dictate.database.entity.InsertionMethod
import net.devemperor.dictate.database.entity.MessageRole
import net.devemperor.dictate.database.entity.ProcessingStepEntity
import net.devemperor.dictate.database.entity.SessionEntity
import net.devemperor.dictate.database.entity.SessionOrigin
import net.devemperor.dictate.database.entity.SessionStatus
import net.devemperor.dictate.database.entity.SessionType
import net.devemperor.dictate.database.entity.StepStatus
import net.devemperor.dictate.database.entity.StepType
import net.devemperor.dictate.database.entity.TextInsertionEntity
import net.devemperor.dictate.database.entity.TranscriptionEntity
import java.util.UUID

/**
 * Orchestrates session persistence with business logic (validation, versioning, transactions).
 * Placed in core/ alongside RecordingManager/PromptQueueManager — not a pure data-access layer.
 */
class SessionManager(private val db: DictateDatabase) {

    private val sessionDao = db.sessionDao()
    private val transcriptionDao = db.transcriptionDao()
    private val stepDao = db.processingStepDao()
    private val completionLogDao = db.completionLogDao()
    private val textInsertionDao = db.textInsertionDao()
    private val conversationDao = db.conversationMessageDao()

    // region Session lifecycle

    /**
     * Atomic session creation with all fields set at once.
     *
     * REPLACES the old signature that took fewer fields and wrote denormalized
     * values later. After this refactor, every session starts life with correct
     * audioDurationSeconds, origin, queuedPromptIds, and initialStatus — no
     * more partial rows that need healing.
     *
     * @param id       the session ID (pre-generated by the caller, so the audio
     *                 file can be persisted under the same name before the row is
     *                 inserted).
     * @return the session ID (same as [id]).
     */
    fun createSession(
        id: String,
        type: SessionType,
        targetApp: String?,
        language: String?,
        audioFilePath: String?,
        audioDurationSeconds: Long,
        parentId: String?,
        origin: SessionOrigin,
        queuedPromptIds: String?,
        initialStatus: SessionStatus
    ): String {
        // Type-specific validation
        when (type) {
            SessionType.RECORDING -> {
                // RECORDING sessions should have audio info
            }
            SessionType.REWORDING -> {
                require(audioFilePath == null) { "REWORDING sessions must not have audio" }
                require(parentId == null) { "REWORDING sessions must not have a parent" }
            }
            SessionType.POST_PROCESSING -> {
                require(audioFilePath == null) { "POST_PROCESSING sessions must not have audio" }
                require(parentId != null) { "POST_PROCESSING sessions must have a parent_session_id" }
            }
        }

        sessionDao.insert(
            SessionEntity(
                id = id,
                type = type.name,
                createdAt = System.currentTimeMillis(),
                targetAppPackage = targetApp,
                language = language,
                audioFilePath = audioFilePath,
                audioDurationSeconds = audioDurationSeconds,
                parentSessionId = parentId,
                status = initialStatus.name,
                origin = origin.name,
                queuedPromptIds = queuedPromptIds
            )
        )
        return id
    }

    /**
     * Returns the session with the given ID, or null if it doesn't exist.
     */
    fun getSessionById(sessionId: String): SessionEntity? = sessionDao.getById(sessionId)

    // ── Terminal status writes ──

    /** Sets status = COMPLETED. */
    fun finalizeCompleted(sessionId: String) {
        sessionDao.updateStatus(sessionId, SessionStatus.COMPLETED.name)
    }

    /** Sets status = CANCELLED + clears last_error_type/message (Finding CA-1). */
    fun finalizeCancelled(sessionId: String) {
        sessionDao.updateStatus(sessionId, SessionStatus.CANCELLED.name)
        sessionDao.updateError(sessionId, null, null)
    }

    /** Sets status = FAILED and stores the error context. */
    fun finalizeFailed(sessionId: String, errorType: String, errorMessage: String) {
        sessionDao.updateStatus(sessionId, SessionStatus.FAILED.name)
        sessionDao.updateError(sessionId, errorType, errorMessage)
    }

    // ── Live-state writes (Spec 1 §6.1 + §6.2 checkpoint hooks) ──
    //
    // Persistenz-Vertrag: DB-first, then ActiveJobRegistry update (KG-SST-5).
    // The module-EffectHandler (RecordingModule / PipelineModule)
    // calls one of these methods first, then updates the registry.
    // No suspend / no explicit transaction — same single-statement
    // pattern as `finalizeCompleted` above (synchronous; callers
    // dispatch on an IO executor; comment CA-1 in `finalizeCancelled`
    // documents the trade-off).

    /**
     * Sets `status = RECORDING`. Called from
     * `RecordingModule.runEffect(Effect.PersistStatus(RECORDING))` at
     * the recording-start checkpoint (Spec 1 §6.2).
     */
    fun transitionRecording(sessionId: String) {
        sessionDao.updateStatus(sessionId, SessionStatus.RECORDING.name)
    }

    /**
     * Sets `status = RECORDED` and persists the final audio file path
     * in one go. Called from
     * `RecordingModule.runEffect(Effect.PersistRecorded)` at
     * recording-stop (Spec 1 §6.2).
     */
    fun transitionRecorded(sessionId: String, audioFilePath: String) {
        sessionDao.updateStatus(sessionId, SessionStatus.RECORDED.name)
        sessionDao.updateAudioFilePath(sessionId, audioFilePath)
    }

    /**
     * Recovery-chain SEND-path reconciliation (2026-05-22). Transition
     * a row that was already inserted at recording-start
     * (`status = RECORDING`, via
     * `PipelineSessionRepoSubsystem.createRecordingSession`) to
     * `RECORDED`, filling the session metadata the SEND path resolved.
     *
     * Used by [net.devemperor.dictate.core.PipelineOrchestrator] in
     * place of [createSession] when the row already exists — a second
     * `createSession` would hit `SessionDao.insert`'s default `ABORT`
     * conflict strategy and throw.
     *
     * Unlike [transitionRecorded] this **does not touch the audio-path
     * columns**: `audio_file_path` / `audio_file_paths` are owned by the
     * recording-start insert + the `SyncAudioSegments` effects, which
     * have already populated the full rolling-segment list. Re-writing
     * a single path here would collapse a multi-segment recording back
     * to its first segment.
     */
    fun finalizeRecordedFromRecordingRow(
        sessionId: String,
        targetApp: String?,
        language: String?,
        audioDurationSeconds: Long,
        queuedPromptIds: String?,
    ) {
        sessionDao.finalizeRecordedMetadata(
            id = sessionId,
            status = SessionStatus.RECORDED.name,
            targetApp = targetApp,
            language = language,
            durationSeconds = audioDurationSeconds,
            queuedPromptIds = queuedPromptIds,
        )
    }

    /**
     * Sets `status = TRANSCRIBING`. Called from
     * `PipelineModule.runEffect(Effect.PersistStatus(TRANSCRIBING))`
     * at pipeline-start (Spec 1 §6.2).
     */
    fun transitionTranscribing(sessionId: String) {
        sessionDao.updateStatus(sessionId, SessionStatus.TRANSCRIBING.name)
    }

    /**
     * Sets the `inserted_at` timestamp on the session. Called from
     * `PipelineModule.runEffect(Effect.ConfirmInsertion)` once the
     * result text has been pushed into the editor (Spec 1 §6.1 + §6.2).
     */
    fun markInserted(sessionId: String, timestamp: Long = System.currentTimeMillis()) {
        sessionDao.markInserted(sessionId, timestamp)
    }

    /**
     * Reads the historical queued prompt IDs for a session. Reads directly from
     * [SessionEntity.queuedPromptIds] — does NOT reconstruct from processing steps.
     * Returns an empty list if the session has no stored queue.
     */
    fun getHistoricalQueuedPromptIds(sessionId: String): List<Int> {
        val raw = sessionDao.getById(sessionId)?.queuedPromptIds ?: return emptyList()
        if (raw.isBlank()) return emptyList()
        return raw.split(",").mapNotNull { it.trim().toIntOrNull() }
    }

    // endregion

    // region Transcription versioning

    /**
     * Adds a new transcription version for the session.
     * Marks previous current version as non-current within a transaction.
     * @return the generated transcription ID
     */
    fun addTranscriptionVersion(
        sessionId: String,
        text: String,
        modelUsed: String,
        provider: String,
        promptTokens: Long = 0,
        completionTokens: Long = 0,
        durationMs: Long
    ): String {
        val id = UUID.randomUUID().toString()
        db.runInTransaction {
            val newVersion = transcriptionDao.getMaxVersion(sessionId) + 1
            transcriptionDao.clearCurrent(sessionId)
            transcriptionDao.insert(
                TranscriptionEntity(
                    id = id,
                    sessionId = sessionId,
                    version = newVersion,
                    isCurrent = true,
                    text = text,
                    modelUsed = modelUsed,
                    provider = provider,
                    promptTokens = promptTokens,
                    completionTokens = completionTokens,
                    durationMs = durationMs,
                    createdAt = System.currentTimeMillis()
                )
            )
        }
        return id
    }

    // endregion

    // region Processing step chain management

    /**
     * Appends a new processing step at the end of the current chain.
     * @return the generated step ID
     */
    fun appendProcessingStep(
        sessionId: String,
        stepType: StepType,
        inputText: String,
        outputText: String?,
        modelUsed: String,
        provider: String,
        promptUsed: String? = null,
        promptEntityId: Int? = null,
        previousStepId: String? = null,
        previousTranscriptionId: String? = null,
        sourceSessionId: String? = null,
        promptTokens: Long = 0,
        completionTokens: Long = 0,
        durationMs: Long,
        status: StepStatus,
        errorMessage: String? = null,
        assistantMessage: String? = null,
        responseFormat: String? = null
    ): String {
        val id = UUID.randomUUID().toString()
        db.runInTransaction {
            val chainIndex = stepDao.getMaxChainIndex(sessionId) + 1
            stepDao.insert(
                ProcessingStepEntity(
                    id = id,
                    sessionId = sessionId,
                    stepType = stepType.name,
                    chainIndex = chainIndex,
                    version = 1,
                    isCurrent = true,
                    inputText = inputText,
                    outputText = outputText,
                    modelUsed = modelUsed,
                    provider = provider,
                    promptUsed = promptUsed,
                    promptEntityId = promptEntityId,
                    previousStepId = previousStepId,
                    previousTranscriptionId = previousTranscriptionId,
                    sourceSessionId = sourceSessionId,
                    promptTokens = promptTokens,
                    completionTokens = completionTokens,
                    durationMs = durationMs,
                    status = status.name,
                    errorMessage = errorMessage,
                    createdAt = System.currentTimeMillis(),
                    assistantMessage = assistantMessage,
                    responseFormat = responseFormat
                )
            )
        }
        return id
    }

    /**
     * Regenerates a processing step at the given chain index.
     * Invalidates all downstream steps and creates a new version at that index.
     * @return the generated step ID
     */
    fun regenerateProcessingStep(
        sessionId: String,
        chainIndex: Int,
        stepType: StepType,
        inputText: String,
        outputText: String?,
        modelUsed: String,
        provider: String,
        promptUsed: String? = null,
        promptEntityId: Int? = null,
        previousStepId: String? = null,
        previousTranscriptionId: String? = null,
        sourceSessionId: String? = null,
        promptTokens: Long = 0,
        completionTokens: Long = 0,
        durationMs: Long,
        status: StepStatus,
        errorMessage: String? = null,
        assistantMessage: String? = null,
        responseFormat: String? = null
    ): String {
        val id = UUID.randomUUID().toString()
        db.runInTransaction {
            val newVersion = stepDao.getMaxVersion(sessionId, chainIndex) + 1
            stepDao.clearCurrentAtIndex(sessionId, chainIndex)
            stepDao.invalidateDownstream(sessionId, chainIndex)
            stepDao.insert(
                ProcessingStepEntity(
                    id = id,
                    sessionId = sessionId,
                    stepType = stepType.name,
                    chainIndex = chainIndex,
                    version = newVersion,
                    isCurrent = true,
                    inputText = inputText,
                    outputText = outputText,
                    modelUsed = modelUsed,
                    provider = provider,
                    promptUsed = promptUsed,
                    promptEntityId = promptEntityId,
                    previousStepId = previousStepId,
                    previousTranscriptionId = previousTranscriptionId,
                    sourceSessionId = sourceSessionId,
                    promptTokens = promptTokens,
                    completionTokens = completionTokens,
                    durationMs = durationMs,
                    status = status.name,
                    errorMessage = errorMessage,
                    createdAt = System.currentTimeMillis(),
                    assistantMessage = assistantMessage,
                    responseFormat = responseFormat
                )
            )
        }
        return id
    }

    // endregion

    // region Conversation turns (ADR-0012)

    /**
     * Appends one conversational turn: the consolidated user message plus the
     * merged assistant step (`CONVERSATION_TURN`), written atomically. On the
     * first turn a `SYSTEM` row is persisted so a later continuation replays the
     * exact system prompt in effect at turn 0 (survives template changes).
     *
     * Assistant turns are NOT stored as message rows — they are reconstructed
     * from the current step chain (design decision D-B); no duplicated cache.
     *
     * @param inputText raw text the turn applied to (transcript for turn 0),
     *   persisted on the step for `getFinalOutput` / audit.
     * @return the new step's id.
     */
    fun appendConversationTurn(
        sessionId: String,
        userMessageContent: String,
        inputText: String,
        result: ConversationResult,
        provider: String,
        previousTranscriptionId: String?,
        durationMs: Long,
        systemPromptForFirstTurn: String?
    ): String {
        var stepId = ""
        db.runInTransaction {
            val chainIndex = stepDao.getMaxChainIndex(sessionId) + 1
            insertTurnUserMessage(sessionId, chainIndex, userMessageContent, systemPromptForFirstTurn)
            stepId = appendProcessingStep(
                sessionId = sessionId,
                stepType = StepType.CONVERSATION_TURN,
                inputText = inputText,
                outputText = result.output,
                modelUsed = result.modelName,
                provider = provider,
                promptUsed = null,
                promptEntityId = null,
                previousStepId = null,
                previousTranscriptionId = previousTranscriptionId,
                sourceSessionId = null,
                promptTokens = result.promptTokens,
                completionTokens = result.completionTokens,
                durationMs = durationMs,
                status = StepStatus.SUCCESS,
                errorMessage = null,
                assistantMessage = result.message,
                responseFormat = result.responseFormat.name
            )
        }
        return stepId
    }

    /**
     * Persists a failed conversational turn: the user message plus an ERROR
     * merged step (output stays at the prior text via `getFinalOutput`), so the
     * attempt is auditable and the conversation carries the user turn.
     */
    fun appendConversationTurnError(
        sessionId: String,
        userMessageContent: String,
        inputText: String,
        model: String,
        provider: String,
        previousTranscriptionId: String?,
        errorMessage: String?,
        durationMs: Long,
        systemPromptForFirstTurn: String?
    ): String {
        var stepId = ""
        db.runInTransaction {
            val chainIndex = stepDao.getMaxChainIndex(sessionId) + 1
            insertTurnUserMessage(sessionId, chainIndex, userMessageContent, systemPromptForFirstTurn)
            stepId = appendProcessingStep(
                sessionId = sessionId,
                stepType = StepType.CONVERSATION_TURN,
                inputText = inputText,
                outputText = null,
                modelUsed = model,
                provider = provider,
                promptUsed = null,
                promptEntityId = null,
                previousStepId = null,
                previousTranscriptionId = previousTranscriptionId,
                sourceSessionId = null,
                promptTokens = 0,
                completionTokens = 0,
                durationMs = durationMs,
                status = StepStatus.ERROR,
                errorMessage = errorMessage,
                assistantMessage = null,
                responseFormat = null
            )
        }
        return stepId
    }

    /**
     * Re-runs a conversational turn at [chainIndex] (F-108 regenerate): a new
     * step version at the same index, replaying the same conversation state.
     * The conversation `USER` rows are NOT touched — the history is unchanged.
     */
    fun regenerateConversationTurn(
        sessionId: String,
        chainIndex: Int,
        result: ConversationResult,
        provider: String,
        durationMs: Long
    ): String {
        val target = stepDao.getCurrentChain(sessionId).firstOrNull { it.chainIndex == chainIndex }
            ?: throw IllegalStateException(
                "No current step at chain_index=$chainIndex for session=$sessionId"
            )
        val stepId = regenerateProcessingStep(
            sessionId = sessionId,
            chainIndex = chainIndex,
            stepType = StepType.CONVERSATION_TURN,
            inputText = target.inputText,
            outputText = result.output,
            modelUsed = result.modelName,
            provider = provider,
            promptUsed = target.promptUsed,
            promptEntityId = target.promptEntityId,
            previousStepId = target.previousStepId,
            previousTranscriptionId = target.previousTranscriptionId,
            sourceSessionId = target.sourceSessionId,
            promptTokens = result.promptTokens,
            completionTokens = result.completionTokens,
            durationMs = durationMs,
            status = StepStatus.SUCCESS,
            errorMessage = null,
            assistantMessage = result.message,
            responseFormat = result.responseFormat.name
        )
        updateFinalOutputText(sessionId, getFinalOutput(sessionId))
        return stepId
    }

    /**
     * Loads the persisted conversation for replay: the system prompt (from the
     * SYSTEM row) plus one [ReconstructedTurn] per successful turn (USER content
     * from `conversation_messages` ⋈ current step output/message by turn index).
     * Failed turns are skipped so the replay carries only real answers.
     */
    fun loadConversation(sessionId: String): ConversationSnapshot {
        val system = conversationDao.getSystemContent(sessionId)
        val userMessages = conversationDao.getUserMessages(sessionId)
        val stepByIndex = stepDao.getCurrentChain(sessionId)
            .filter { it.stepType == StepType.CONVERSATION_TURN.name }
            .associateBy { it.chainIndex }
        val turns = userMessages.mapNotNull { user ->
            val step = stepByIndex[user.turnIndex] ?: return@mapNotNull null
            if (step.status != StepStatus.SUCCESS.name || step.outputText == null) return@mapNotNull null
            ReconstructedTurn(user.content, step.outputText, step.assistantMessage)
        }
        return ConversationSnapshot(system, turns)
    }

    /**
     * The `message` field of the last successful conversational turn — the
     * "durchgereicht" hook Paket 2's review modes read. Null when the session
     * has no successful conversation turn.
     */
    fun getAssistantMessage(sessionId: String): String? {
        return stepDao.getCurrentChain(sessionId)
            .lastOrNull {
                it.stepType == StepType.CONVERSATION_TURN.name &&
                    it.status == StepStatus.SUCCESS.name
            }
            ?.assistantMessage
    }

    /** Inserts the per-turn USER row (+ the SYSTEM row on the first turn). */
    private fun insertTurnUserMessage(
        sessionId: String,
        chainIndex: Int,
        userMessageContent: String,
        systemPromptForFirstTurn: String?
    ) {
        var seq = conversationDao.getMaxSeq(sessionId)
        if (seq < 0 && !systemPromptForFirstTurn.isNullOrEmpty()) {
            seq += 1
            conversationDao.insert(
                ConversationMessageEntity(
                    id = UUID.randomUUID().toString(),
                    sessionId = sessionId,
                    turnIndex = -1,
                    seq = seq,
                    role = MessageRole.SYSTEM.name,
                    content = systemPromptForFirstTurn,
                    stepId = null,
                    createdAt = System.currentTimeMillis()
                )
            )
        }
        seq += 1
        conversationDao.insert(
            ConversationMessageEntity(
                id = UUID.randomUUID().toString(),
                sessionId = sessionId,
                turnIndex = chainIndex,
                seq = seq,
                role = MessageRole.USER.name,
                content = userMessageContent,
                stepId = null,
                createdAt = System.currentTimeMillis()
            )
        )
    }

    // endregion

    // region Completion logging

    /**
     * Logs an AI API call (transcription or processing step).
     */
    fun logCompletion(
        type: String,
        sessionId: String?,
        stepId: String? = null,
        transcriptionId: String? = null,
        systemPrompt: String? = null,
        userPrompt: String? = null,
        success: Boolean,
        errorMessage: String? = null
    ) {
        completionLogDao.insert(
            CompletionLogEntity(
                timestamp = System.currentTimeMillis(),
                type = type,
                sessionId = sessionId,
                stepId = stepId,
                transcriptionId = transcriptionId,
                systemPrompt = systemPrompt,
                userPrompt = userPrompt,
                success = success,
                errorMessage = errorMessage
            )
        )
    }

    // endregion

    // region Text insertion logging

    /**
     * Logs a text insertion (commit or paste) into the target app.
     */
    fun logTextInsertion(
        sessionId: String?,
        text: String,
        replacedText: String? = null,
        targetAppPackage: String? = null,
        cursorPosition: Int? = null,
        sourceStepId: String? = null,
        sourceTranscriptionId: String? = null,
        method: InsertionMethod
    ) {
        textInsertionDao.insert(
            TextInsertionEntity(
                sessionId = sessionId,
                timestamp = System.currentTimeMillis(),
                insertedText = text,
                replacedText = replacedText,
                targetAppPackage = targetAppPackage,
                cursorPosition = cursorPosition,
                sourceStepId = sourceStepId,
                sourceTranscriptionId = sourceTranscriptionId,
                insertionMethod = method.name
            )
        )
    }

    /**
     * Convenience method for logging a paste from history.
     */
    fun logPasteFromHistory(
        sessionId: String?,
        sourceStepId: String?,
        sourceTranscriptionId: String?,
        text: String
    ) {
        logTextInsertion(
            sessionId = sessionId,
            text = text,
            sourceStepId = sourceStepId,
            sourceTranscriptionId = sourceTranscriptionId,
            method = InsertionMethod.PASTE
        )
    }

    // endregion

    // region Query helpers

    /**
     * Returns the final output text for a session.
     * Fallback chain: last current step output > current transcription > denormalized field.
     * The denormalized field is only populated if callers explicitly call [updateFinalOutputText].
     */
    fun getFinalOutput(sessionId: String): String? {
        val chain = stepDao.getCurrentChain(sessionId)
        if (chain.isNotEmpty()) {
            val lastStep = chain.last()
            if (lastStep.status == StepStatus.SUCCESS.name && lastStep.outputText != null) {
                return lastStep.outputText
            }
        }
        val transcription = transcriptionDao.getCurrent(sessionId)
        if (transcription != null) {
            return transcription.text
        }
        return sessionDao.getById(sessionId)?.finalOutputText
    }

    /**
     * Returns the final output with source information for traceability.
     */
    fun getFinalOutputSource(sessionId: String): FinalOutputInfo? {
        val chain = stepDao.getCurrentChain(sessionId)
        if (chain.isNotEmpty()) {
            val lastStep = chain.last()
            if (lastStep.status == StepStatus.SUCCESS.name && lastStep.outputText != null) {
                return FinalOutputInfo(
                    text = lastStep.outputText,
                    stepId = lastStep.id,
                    transcriptionId = null
                )
            }
        }
        val transcription = transcriptionDao.getCurrent(sessionId)
        if (transcription != null) {
            return FinalOutputInfo(
                text = transcription.text,
                stepId = null,
                transcriptionId = transcription.id
            )
        }
        return null
    }

    /**
     * Returns the output text of a specific processing step by ID.
     */
    fun getStepOutput(stepId: String): String? {
        return stepDao.getById(stepId)?.outputText
    }

    /**
     * Returns the text of a specific transcription version by ID.
     */
    fun getTranscriptionText(transcriptionId: String): String? {
        return transcriptionDao.getById(transcriptionId)?.text
    }

    /**
     * Updates the denormalized final_output_text on the session entity.
     */
    fun updateFinalOutputText(sessionId: String, text: String?) {
        sessionDao.updateFinalOutputText(sessionId, text)
    }

    /**
     * Updates the denormalized input_text on the session entity.
     * For REWORDING: the selected text. For POST_PROCESSING: the parent session's output.
     */
    fun updateInputText(sessionId: String, text: String?) {
        sessionDao.updateInputText(sessionId, text)
    }

    /**
     * Updates the audio duration after audio file has been persisted.
     */
    fun updateAudioDuration(sessionId: String, durationSeconds: Long) {
        sessionDao.updateAudioDuration(sessionId, durationSeconds)
    }

    // endregion

    /**
     * Holds the final output text with its source reference for Java interop.
     */
    data class FinalOutputInfo(
        val text: String,
        val stepId: String?,
        val transcriptionId: String?
    )

    /**
     * The persisted conversation, ready for replay (ADR-0012): the system prompt
     * (or null) plus the successful turns in order. Feed [turns] to
     * [net.devemperor.dictate.ai.conversation.ConversationReconstructor].
     */
    data class ConversationSnapshot(
        val systemContent: String?,
        val turns: List<ReconstructedTurn>
    )
}
