package net.devemperor.dictate.core

import net.devemperor.dictate.database.DictateDatabase
import net.devemperor.dictate.database.entity.CompletionLogEntity
import net.devemperor.dictate.database.entity.InsertionMethod
import net.devemperor.dictate.database.entity.ProcessingStepEntity
import net.devemperor.dictate.database.entity.SessionEntity
import net.devemperor.dictate.database.entity.SessionOrigin
import net.devemperor.dictate.database.entity.SessionStatus
import net.devemperor.dictate.database.entity.SessionType
import net.devemperor.dictate.database.entity.StepStatus
import net.devemperor.dictate.database.entity.StepType
import net.devemperor.dictate.database.entity.TextInsertionEntity
import net.devemperor.dictate.database.entity.TranscriptionEntity
import java.util.UUID

/**
 * Orchestrates session persistence with business logic (validation, versioning, transactions).
 * Placed in core/ alongside RecordingManager/PromptQueueManager — not a pure data-access layer.
 */
class SessionManager(private val db: DictateDatabase) {

    private val sessionDao = db.sessionDao()
    private val transcriptionDao = db.transcriptionDao()
    private val stepDao = db.processingStepDao()
    private val completionLogDao = db.completionLogDao()
    private val textInsertionDao = db.textInsertionDao()

    // region Session lifecycle

    /**
     * Atomic session creation with all fields set at once.
     *
     * REPLACES the old signature that took fewer fields and wrote denormalized
     * values later. After this refactor, every session starts life with correct
     * audioDurationSeconds, origin, queuedPromptIds, and initialStatus — no
     * more partial rows that need healing.
     *
     * @param id       the session ID (pre-generated by the caller, so the audio
     *                 file can be persisted under the same name before the row is
     *                 inserted).
     * @return the session ID (same as [id]).
     */
    fun createSession(
        id: String,
        type: SessionType,
        targetApp: String?,
        language: String?,
        audioFilePath: String?,
        audioDurationSeconds: Long,
        parentId: String?,
        origin: SessionOrigin,
        queuedPromptIds: String?,
        initialStatus: SessionStatus
    ): String {
        // Type-specific validation
        when (type) {
            SessionType.RECORDING -> {
                // RECORDING sessions should have audio info
            }
            SessionType.REWORDING -> {
                require(audioFilePath == null) { "REWORDING sessions must not have audio" }
                require(parentId == null) { "REWORDING sessions must not have a parent" }
            }
            SessionType.POST_PROCESSING -> {
                require(audioFilePath == null) { "POST_PROCESSING sessions must not have audio" }
                require(parentId != null) { "POST_PROCESSING sessions must have a parent_session_id" }
            }
        }

        sessionDao.insert(
            SessionEntity(
                id = id,
                type = type.name,
                createdAt = System.currentTimeMillis(),
                targetAppPackage = targetApp,
                language = language,
                audioFilePath = audioFilePath,
                audioDurationSeconds = audioDurationSeconds,
                parentSessionId = parentId,
                status = initialStatus.name,
                origin = origin.name,
                queuedPromptIds = queuedPromptIds
            )
        )
        return id
    }

    /**
     * Returns the session with the given ID, or null if it doesn't exist.
     */
    fun getSessionById(sessionId: String): SessionEntity? = sessionDao.getById(sessionId)

    // ── Terminal status writes ──

    /** Sets status = COMPLETED. */
    fun finalizeCompleted(sessionId: String) {
        sessionDao.updateStatus(sessionId, SessionStatus.COMPLETED.name)
    }

    /** Sets status = CANCELLED + clears last_error_type/message (Finding CA-1). */
    fun finalizeCancelled(sessionId: String) {
        sessionDao.updateStatus(sessionId, SessionStatus.CANCELLED.name)
        sessionDao.updateError(sessionId, null, null)
    }

    /** Sets status = FAILED and stores the error context. */
    fun finalizeFailed(sessionId: String, errorType: String, errorMessage: String) {
        sessionDao.updateStatus(sessionId, SessionStatus.FAILED.name)
        sessionDao.updateError(sessionId, errorType, errorMessage)
    }

    /**
     * Reads the historical queued prompt IDs for a session. Reads directly from
     * [SessionEntity.queuedPromptIds] — does NOT reconstruct from processing steps.
     * Returns an empty list if the session has no stored queue.
     */
    fun getHistoricalQueuedPromptIds(sessionId: String): List<Int> {
        val raw = sessionDao.getById(sessionId)?.queuedPromptIds ?: return emptyList()
        if (raw.isBlank()) return emptyList()
        return raw.split(",").mapNotNull { it.trim().toIntOrNull() }
    }

    // endregion

    // region Transcription versioning

    /**
     * Adds a new transcription version for the session.
     * Marks previous current version as non-current within a transaction.
     * @return the generated transcription ID
     */
    fun addTranscriptionVersion(
        sessionId: String,
        text: String,
        modelUsed: String,
        provider: String,
        promptTokens: Long = 0,
        completionTokens: Long = 0,
        durationMs: Long
    ): String {
        val id = UUID.randomUUID().toString()
        db.runInTransaction {
            val newVersion = transcriptionDao.getMaxVersion(sessionId) + 1
            transcriptionDao.clearCurrent(sessionId)
            transcriptionDao.insert(
                TranscriptionEntity(
                    id = id,
                    sessionId = sessionId,
                    version = newVersion,
                    isCurrent = true,
                    text = text,
                    modelUsed = modelUsed,
                    provider = provider,
                    promptTokens = promptTokens,
                    completionTokens = completionTokens,
                    durationMs = durationMs,
                    createdAt = System.currentTimeMillis()
                )
            )
        }
        return id
    }

    // endregion

    // region Processing step chain management

    /**
     * Appends a new processing step at the end of the current chain.
     * @return the generated step ID
     */
    fun appendProcessingStep(
        sessionId: String,
        stepType: StepType,
        inputText: String,
        outputText: String?,
        modelUsed: String,
        provider: String,
        promptUsed: String? = null,
        promptEntityId: Int? = null,
        previousStepId: String? = null,
        previousTranscriptionId: String? = null,
        sourceSessionId: String? = null,
        promptTokens: Long = 0,
        completionTokens: Long = 0,
        durationMs: Long,
        status: StepStatus,
        errorMessage: String? = null
    ): String {
        val id = UUID.randomUUID().toString()
        db.runInTransaction {
            val chainIndex = stepDao.getMaxChainIndex(sessionId) + 1
            stepDao.insert(
                ProcessingStepEntity(
                    id = id,
                    sessionId = sessionId,
                    stepType = stepType.name,
                    chainIndex = chainIndex,
                    version = 1,
                    isCurrent = true,
                    inputText = inputText,
                    outputText = outputText,
                    modelUsed = modelUsed,
                    provider = provider,
                    promptUsed = promptUsed,
                    promptEntityId = promptEntityId,
                    previousStepId = previousStepId,
                    previousTranscriptionId = previousTranscriptionId,
                    sourceSessionId = sourceSessionId,
                    promptTokens = promptTokens,
                    completionTokens = completionTokens,
                    durationMs = durationMs,
                    status = status.name,
                    errorMessage = errorMessage,
                    createdAt = System.currentTimeMillis()
                )
            )
        }
        return id
    }

    /**
     * Regenerates a processing step at the given chain index.
     * Invalidates all downstream steps and creates a new version at that index.
     * @return the generated step ID
     */
    fun regenerateProcessingStep(
        sessionId: String,
        chainIndex: Int,
        stepType: StepType,
        inputText: String,
        outputText: String?,
        modelUsed: String,
        provider: String,
        promptUsed: String? = null,
        promptEntityId: Int? = null,
        previousStepId: String? = null,
        previousTranscriptionId: String? = null,
        sourceSessionId: String? = null,
        promptTokens: Long = 0,
        completionTokens: Long = 0,
        durationMs: Long,
        status: StepStatus,
        errorMessage: String? = null
    ): String {
        val id = UUID.randomUUID().toString()
        db.runInTransaction {
            val newVersion = stepDao.getMaxVersion(sessionId, chainIndex) + 1
            stepDao.clearCurrentAtIndex(sessionId, chainIndex)
            stepDao.invalidateDownstream(sessionId, chainIndex)
            stepDao.insert(
                ProcessingStepEntity(
                    id = id,
                    sessionId = sessionId,
                    stepType = stepType.name,
                    chainIndex = chainIndex,
                    version = newVersion,
                    isCurrent = true,
                    inputText = inputText,
                    outputText = outputText,
                    modelUsed = modelUsed,
                    provider = provider,
                    promptUsed = promptUsed,
                    promptEntityId = promptEntityId,
                    previousStepId = previousStepId,
                    previousTranscriptionId = previousTranscriptionId,
                    sourceSessionId = sourceSessionId,
                    promptTokens = promptTokens,
                    completionTokens = completionTokens,
                    durationMs = durationMs,
                    status = status.name,
                    errorMessage = errorMessage,
                    createdAt = System.currentTimeMillis()
                )
            )
        }
        return id
    }

    // endregion

    // region Completion logging

    /**
     * Logs an AI API call (transcription or processing step).
     */
    fun logCompletion(
        type: String,
        sessionId: String?,
        stepId: String? = null,
        transcriptionId: String? = null,
        systemPrompt: String? = null,
        userPrompt: String? = null,
        success: Boolean,
        errorMessage: String? = null
    ) {
        completionLogDao.insert(
            CompletionLogEntity(
                timestamp = System.currentTimeMillis(),
                type = type,
                sessionId = sessionId,
                stepId = stepId,
                transcriptionId = transcriptionId,
                systemPrompt = systemPrompt,
                userPrompt = userPrompt,
                success = success,
                errorMessage = errorMessage
            )
        )
    }

    // endregion

    // region Text insertion logging

    /**
     * Logs a text insertion (commit or paste) into the target app.
     */
    fun logTextInsertion(
        sessionId: String?,
        text: String,
        replacedText: String? = null,
        targetAppPackage: String? = null,
        cursorPosition: Int? = null,
        sourceStepId: String? = null,
        sourceTranscriptionId: String? = null,
        method: InsertionMethod
    ) {
        textInsertionDao.insert(
            TextInsertionEntity(
                sessionId = sessionId,
                timestamp = System.currentTimeMillis(),
                insertedText = text,
                replacedText = replacedText,
                targetAppPackage = targetAppPackage,
                cursorPosition = cursorPosition,
                sourceStepId = sourceStepId,
                sourceTranscriptionId = sourceTranscriptionId,
                insertionMethod = method.name
            )
        )
    }

    /**
     * Convenience method for logging a paste from history.
     */
    fun logPasteFromHistory(
        sessionId: String?,
        sourceStepId: String?,
        sourceTranscriptionId: String?,
        text: String
    ) {
        logTextInsertion(
            sessionId = sessionId,
            text = text,
            sourceStepId = sourceStepId,
            sourceTranscriptionId = sourceTranscriptionId,
            method = InsertionMethod.PASTE
        )
    }

    // endregion

    // region Query helpers

    /**
     * Returns the final output text for a session.
     * Fallback chain: last current step output > current transcription > denormalized field.
     * The denormalized field is only populated if callers explicitly call [updateFinalOutputText].
     */
    fun getFinalOutput(sessionId: String): String? {
        val chain = stepDao.getCurrentChain(sessionId)
        if (chain.isNotEmpty()) {
            val lastStep = chain.last()
            if (lastStep.status == StepStatus.SUCCESS.name && lastStep.outputText != null) {
                return lastStep.outputText
            }
        }
        val transcription = transcriptionDao.getCurrent(sessionId)
        if (transcription != null) {
            return transcription.text
        }
        return sessionDao.getById(sessionId)?.finalOutputText
    }

    /**
     * Returns the final output with source information for traceability.
     */
    fun getFinalOutputSource(sessionId: String): FinalOutputInfo? {
        val chain = stepDao.getCurrentChain(sessionId)
        if (chain.isNotEmpty()) {
            val lastStep = chain.last()
            if (lastStep.status == StepStatus.SUCCESS.name && lastStep.outputText != null) {
                return FinalOutputInfo(
                    text = lastStep.outputText,
                    stepId = lastStep.id,
                    transcriptionId = null
                )
            }
        }
        val transcription = transcriptionDao.getCurrent(sessionId)
        if (transcription != null) {
            return FinalOutputInfo(
                text = transcription.text,
                stepId = null,
                transcriptionId = transcription.id
            )
        }
        return null
    }

    /**
     * Returns the output text of a specific processing step by ID.
     */
    fun getStepOutput(stepId: String): String? {
        return stepDao.getById(stepId)?.outputText
    }

    /**
     * Returns the text of a specific transcription version by ID.
     */
    fun getTranscriptionText(transcriptionId: String): String? {
        return transcriptionDao.getById(transcriptionId)?.text
    }

    /**
     * Updates the denormalized final_output_text on the session entity.
     */
    fun updateFinalOutputText(sessionId: String, text: String?) {
        sessionDao.updateFinalOutputText(sessionId, text)
    }

    /**
     * Updates the denormalized input_text on the session entity.
     * For REWORDING: the selected text. For POST_PROCESSING: the parent session's output.
     */
    fun updateInputText(sessionId: String, text: String?) {
        sessionDao.updateInputText(sessionId, text)
    }

    /**
     * Updates the audio duration after audio file has been persisted.
     */
    fun updateAudioDuration(sessionId: String, durationSeconds: Long) {
        sessionDao.updateAudioDuration(sessionId, durationSeconds)
    }

    // endregion

    /**
     * Holds the final output text with its source reference for Java interop.
     */
    data class FinalOutputInfo(
        val text: String,
        val stepId: String?,
        val transcriptionId: String?
    )
}
